---
- hosts: localhost
  tasks:
      - name: Resolv.conf
        copy: src=/etc/resolv.conf-tmp dest=/etc/resolv.conf
      - name: validation resolv.conf
        command: "nslookup www.google.ca" 
        register: result
        ignore_errors: True
      - name: Revert backp
        lineinfile: path=/etc/resolv.conf line='nameserver 192.168.2.1'
        when: result|failed
