---
- vsphere_guest:
    vcenter_hostname: 192.168.2.50
    username: root
    password: Pass1234
    guest: newvm001
    template: centos-7-template
    state: powered_on
    vm_extra_config:
      vcpu.hotadd: yes
      mem.hotadd:  yes
      notes: This is a test VM
    vm_disk:
      disk1:
        size_gb: 20
        type: thin
        datastore: datastore1
    vm_nic:
      nic1:
        type: vmxnet3
        network: VM Network
        network_type: standard
        type: vmxnet3
        network: VM Network
        network_type: standard
    vm_hardware:
       memory_mb: 1024
       num_cpus: 2
       osid: centos64Guest
       scsi: paravirtual
       esxi:
         datacenter: datastore1
         hostname: 192.168.2.21

