---
# tasks file for disk-managment
- name: Extending 2 /dev/sdb disk partition
  parted: device=/dev/sdb number=2 state=present part_end=2GiB
  register: new_disk_name
- name: adding disk into volume group
  lvg: vg={{ vg_name }}  pvs=/dev/sdb2,{{ old_disk_name}}  state=present
- name: Expending volume group
  lvol: vg={{ vg_name }}  lv={{ lv_name_1 }} size=100%VG
- name: Resize FS
  command: resize2fs  /dev/mapper/{{ vg_name }}-{{ lv_name_1 }}
