---
- name: NFS configuration module for nfs server
  yum: pkg=nfs-utils disable_gpg_check=yes state=present
- name: NFS package 
  yum: pkg=nfs-utils-lib disable_gpg_check=yes state=present
- name: nfs-service
  service: name=nfs state=stopped enabled=yes
- name: exportfs_nfs
  template: src=files/exports.j2 dest=/etc/exports owner=root group=root
